- name: Install homeassistant-cli
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check if homeassistant-cli is installed
      command: hass-cli --version
      register: homeassistant_cli_installed
      changed_when: false
      failed_when: false
      check_mode: false

    - name: Install homeassistant-cli
      pip:
        name: homeassistant-cli
        state: present
      register: homeassistant_cli_installer
      when: homeassistant_cli_installed.rc != 0
