- name: Install homeassistant-cli
  hosts: localhost
  gather_facts: false

  vars:
    hass_server: "{{ lookup('env', 'HASS_SERVER') }}"
    hass_token: "{{ lookup('env', 'HASS_TOKEN') }}"

  tasks:
    - name: Check if homeassistant-cli is installed
      command: hass-cli --version
      register: homeassistant_cli_installed
      changed_when: false
      failed_when: false
      check_mode: false

    - name: Install homeassistant-cli
      pip:
        name: homeassistant-cli
        state: present
      register: homeassistant_cli_installer
      when: homeassistant_cli_installed.rc != 0

    - name: Configure homeassistant-cli environment on .zshrc file
      blockinfile:
        path: ~/.zshrc
        block: |
          export HASS_SERVER={{ hass_server }}
          export HASS_TOKEN={{ hass_token }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - HASS_CLI_ENV"
      tags: config
