---
- name: Initial setup
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
      tags: upgrade

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - apt-utils
        - asciinema
        - build-essential
        - ca-certificates
        - coreutils
        - curl
        - htop
        - jq
        - lsb-release
        - mc
        - nano
        - ncdu
        - net-tools
        - pandoc
        - software-properties-common
        - unzip
        - wget
        - zip
