---
- name: Initial setup
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Check if universe repository is enabled
      shell: apt-cache policy | grep universe
      register: universe_repository
      changed_when: false
      failed_when: false
      check_mode: false
      tags: config

    - name: Add universe repository on Ubuntu
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present
        update_cache: yes
      when: universe_repository.rc != 0 and ansible_distribution == 'Ubuntu'
      tags: config

    - name: Check if multiverse repository is enabled
      shell: apt-cache policy | grep multiverse
      register: multiverse_repository
      changed_when: false
      failed_when: false
      check_mode: false
      tags: config

    - name: Add multiverse repository on Ubuntu
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
        state: present
        update_cache: yes
      when: multiverse_repository.rc != 0 and ansible_distribution == 'Ubuntu'
      tags: config

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
      tags: upgrade

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - ansible-lint
        - apt-transport-https
        - apt-utils
        - asciinema
        - build-essential
        - ca-certificates
        - coreutils
        - csvkit
        - curl
        - elinks
        - htop
        - iputils-ping
        - jq
        - lsb-release
        - mc
        - mtr
        - nano
        - ncdu
        - neofetch
        - net-tools
        - pandoc
        - python-is-python3
        - python3-pip
        - software-properties-common
        - sqlite3
        - unzip
        - wget
        - whois
        - zip

    - name: Add on .bashrc user bin folder to PATH
      blockinfile:
        path: ~/.bashrc
        block: |
          if [ -d "$HOME/bin" ] ; then
            PATH="$HOME/bin:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - bin folder"
      become: false

    - name: Add on .zshrc user bin folder to PATH
      blockinfile:
        path: ~/.zshrc
        block: |
          if [ -d "$HOME/bin" ] ; then
            PATH="$HOME/bin:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - bin folder"
      become: false

    - name: Add on .bashrc user .local/bin folder to PATH
      blockinfile:
        path: ~/.bashrc
        block: |
          if [ -d "$HOME/.local/bin" ] ; then
            PATH="$HOME/.local/bin:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - .local/bin folder"
      become: false

    - name: Add on .zshrc user .local/bin folder to PATH
      blockinfile:
        path: ~/.zshrc
        block: |
          if [ -d "$HOME/.local/bin" ] ; then
            PATH="$HOME/.local/bin:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - .local/bin folder"
      become: false