---
- name: Configure Git username and email
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Add sudoers entry for passwordless sudo
      blockinfile:
        path: /etc/sudoers
        block: |
          lpsouza ALL=(ALL) NOPASSWD:ALL
        marker: "# {mark} ANSIBLE MANAGED BLOCK - passwordless sudo"
      tags: config
