---
- name: Lid closing | Configurations
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Lid closing | Configure handleLidSwitch to ignore
      lineinfile:
        path: /etc/systemd/logind.conf
        regexp: "^#HandleLidSwitch="
        line: "HandleLidSwitch=ignore"

    - name: Lid closing | Configure LidSwitchIgnoreInhibited to no
      lineinfile:
        path: /etc/systemd/logind.conf
        regexp: "^#LidSwitchIgnoreInhibited="
        line: "LidSwitchIgnoreInhibited=no"
