---
- name: Passwordless sudo | Configuration
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Passwordless sudo | Add sudoers entry for the ansible user
      blockinfile:
        path: /etc/sudoers
        block: |
          {{ ansible_user }} ALL=(ALL) NOPASSWD:ALL
        marker: "# {mark} ANSIBLE MANAGED BLOCK - passwordless sudo"
