---
- name: Public key | Installation
  hosts: linux
  gather_facts: false

  vars:
    pubkey: "{{ lookup('env', 'PUBKEY') | default('not set', true) }}"

  tasks:
    - name: Public key | Add public key to authorized_keys
      lineinfile:
        path: ~/.ssh/authorized_keys
        line: "{{ pubkey }}"
        create: true
        mode: 0600
      when: pubkey != "not set"
