---
- name: Install bashtop
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Install bashtop PPA repository
      apt_repository:
        repo: ppa:bashtop-monitor/bashtop
        state: present
        filename: bashtop
      when: ansible_distribution == 'Ubuntu'

    - name: Install bashtop
      apt:
        name: bashtop
        state: present
        update_cache: yes
