---
- name: Install duf
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  vars:
    duf_version: "0.8.0"

  tasks:
    - name: Check if duf is already installed
      shell: dpkg-query -W -f='${Status}' duf || echo "not installed"
      register: duf_package_status
      changed_when: false
      failed_when: duf_package_status.rc != 0

    - name: Download duf
      get_url:
        url: https://github.com/muesli/duf/releases/download/v{{ duf_version }}/duf_{{ duf_version }}_linux_amd64.deb
        dest: /tmp/duf_{{ duf_version }}_linux_amd64.deb
      when: "'not installed' in duf_package_status.stdout"

    - name: Install duf
      apt:
        deb: /tmp/duf_{{ duf_version }}_linux_amd64.deb
        state: present
      when: "'not installed' in duf_package_status.stdout"
