---
- name: Timezone | Configuration
  hosts: linux
  gather_facts: false
  become: true

  vars:
    timezone: "{{ lookup('env', 'TZ') | default('America/Sao_Paulo', true) }}"

  tasks:
    - name: Timezone | Set timezone {{ timezone }}
      timezone:
        name: "{{ timezone }}"
