---
# Install cURL
# https://curl.se/
#
# Description: cURL is a command-line tool for transferring data with URL syntax.
#
- name: cURL | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: cURL | Install curl
      apt:
        name: curl
        state: present
        update_cache: true
