---
# Install Docker
# https://www.docker.com/
#
# Description: Docker is an open platform for developing, shipping, and running applications. Docker enables you to separate your applications from your infrastructure so you can deliver software quickly.
#
- name: Docker | Installation
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Docker | Checking if is already installed
      command: which docker
      register: docker_check
      changed_when: false
      failed_when: false

    - name: Docker | Download installer script
      get_url:
        url: https://get.docker.com
        dest: /tmp/install.sh
        mode: "0755"
      when: docker_check.rc == 1

    - name: Docker | Install
      command: /tmp/install.sh
      when: docker_check.rc == 1

    - name: Docker | Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
        state: present
      when: docker_check.rc == 1
