---
# Install exa
# https://the.exa.website/
#
# Description: exa is a modern replacement for ls, written in Rust.
#
- name: exa | Installation
  hosts: linux
  gather_facts: true
  become: true

  tasks:
    - name: exa | Install
      apt:
        name: exa
        state: present
      register: exa
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 23

    - name: exa | Install (alternative)
      package:
        name: eza
        state: present
      register: exa
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int > 23


    - name: exa | Configure alias for exa to .bashrc if exa is installed
      blockinfile:
        path: ~/.bashrc
        block: |
          alias ls='exa --icons -F -H --group-directories-first'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - exa"
      when: exa is defined and exa.changed
      become: false

    - name: exa | Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: zshrc
      become: false

    - name: exa | Configure alias for exa to .zshrc if exa is installed
      blockinfile:
        path: ~/.zshrc
        block: |
          alias ls='exa --icons -F -H --group-directories-first'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - exa"
      when: exa is defined and exa.changed and zshrc.stat.exists
      become: false
