---
# Install python3 and pip
# https://www.python.org/
#
# Description: Python is a programming language that lets you work quickly and integrate systems more effectively.
#
- name: Python3 | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Python3 | Install python3 and pip
      apt:
        name:
          - python-is-python3
          - python3-pip
        state: present
        update_cache: yes
