---
- name: 1Password | Installation
  hosts: linux
  gather_facts: true
  become: true

  tasks:
    - name: 1Password | Download key
      get_url:
        url: https://downloads.1password.com/linux/keys/1password.asc
        dest: /tmp/1password.asc
        mode: 0755

    - name: 1Password | Add key
      command: gpg --batch --yes --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg /tmp/1password.asc
      changed_when: false

    - name: 1Password | Get architecture
      command: "dpkg --print-architecture"
      register: dpkg_arch
      changed_when: false
      failed_when: false

    - name: 1Password | Add repository
      apt_repository:
        repo: "deb [arch={{ dpkg_arch.stdout }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ dpkg_arch.stdout }} stable main"
        state: present
        filename: 1password

    - name: 1Password | Download policy
      get_url:
        url: https://downloads.1password.com/linux/debian/debsig/1password.pol
        dest: /tmp/1password.pol
        mode: 0755

    - name: 1Password | Create policy directory
      file:
        path: /etc/debsig/policies/AC2D62742012EA22/
        state: directory
        mode: 0755

    - name: 1Password | Add policy
      copy:
        src: /tmp/1password.pol
        dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
        mode: 0755

    - name: 1Password | Create keyring directory
      file:
        path: /usr/share/debsig/keyrings/AC2D62742012EA22
        state: directory
        mode: 0755

    - name: 1Password | Add keyring
      copy:
        src: /tmp/1password.asc
        dest: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
        mode: 0755

    - name: 1Password | Install desktop and cli
      apt:
        name:
          - 1password
          - 1password-cli
        state: present
        update_cache: true

    - name: 1Password | Configure plugin on .bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          alias start-op-desktop='1password --silent'
          if [ -f ~/.config/op/plugins.sh ]; then
            source ~/.config/op/plugins.sh
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - 1Password Plugin"
      become: false

    - name: 1Password | Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: zshrc_check
      become: false

    - name: 1Password | Configure plugin on .zshrc
      blockinfile:
        path: ~/.zshrc
        block: |
          alias start-op-desktop='1password --silent'
          if [ -f ~/.config/op/plugins.sh ]; then
            source ~/.config/op/plugins.sh
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - 1Password Plugin"
      when: zshrc_check.stat.exists
      become: false
