---
- name: DBeaver | Install
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: DBeaver | Download
      get_url:
        url: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
        dest: /tmp/dbeaver-ce_latest_amd64.deb

    - name: DBeaver | Install
      apt:
        deb: /tmp/dbeaver-ce_latest_amd64.deb
        state: present
