---
# Install DBeaver
# https://dbeaver.io/
#
# Description: DBeaver is a free multi-platform database tool for developers, SQL programmers, database administrators and analysts. Supports all popular databases: MySQL, PostgreSQL, SQLite, Oracle, DB2, SQL Server, Sybase, MS Access, Teradata, Firebird, Apache Hive, Phoenix, Presto, etc.
#
- name: DBeaver | Install
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: DBeaver | Download
      get_url:
        url: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
        dest: /tmp/dbeaver-ce_latest_amd64.deb

    - name: DBeaver | Install
      apt:
        deb: /tmp/dbeaver-ce_latest_amd64.deb
        state: present
