---
- name: X Windows | Installation
  hosts: linux
  gather_facts: false
  become: true

  vars:
    # Options: i3, xfce4, wmaker
    install_window_managers: "{{ lookup('env', 'INSTALL_WINDOW_MANAGERS') | default('[\"wmaker\"]', true) | from_json }}"
    default_window_manager: "{{ lookup('env', 'DEFAULT_WINDOW_MANAGER') | default('wmaker', true) }}"

  tasks:
    - name: X Windows | Install X Window System (base)
      apt:
        name:
          - xorg
          - xinit
          - xrdp
        state: present
        update_cache: true

    - name: X Windows | Install i3 window manager
      apt:
        name:
          - i3
          - i3blocks
        state: present
        update_cache: true
      when: install_window_managers is defined and "i3" in install_window_managers

    - name: X Windows | Check if ~/.config/i3 exists
      file:
        path: ~/.config/i3
        state: directory
        recurse: true
        mode: 0755
      when: install_window_managers is defined and "i3" in install_window_managers
      changed_when: false
      become: false

    - name: X Windows | Copy i3 config
      get_url:
        url: https://gist.github.com/lpsouza/9ac2100ce15e43dc57847858903b1849/raw
        dest: ~/.config/i3/config
        mode: "0644"
      when: install_window_managers is defined and "i3" in install_window_managers
      changed_when: false
      become: false

    - name: X Windows | i3status | Check if ~/.config/i3status exists
      file:
        path: ~/.config/i3status
        state: directory
        recurse: true
        mode: 0755
      when: install_window_managers is defined and "i3" in install_window_managers
      changed_when: false
      become: false

    - name: X Windows | i3status | Copy i3status config
      get_url:
        url: https://gist.github.com/lpsouza/408b2d8142caeb27f8dc6645b84fe04d/raw
        dest: ~/.config/i3status/config
        mode: "0644"
      when: install_window_managers is defined and "i3" in install_window_managers
      changed_when: false
      become: false

    - name: X Windows | Set default window manager to i3 (if is set to default)
      shell: |
        set -o pipefail
        rm -f ~/.xsession
        if ! grep -q "exec i3" ~/.xsession; then
          echo "exec i3" >> ~/.xsession
        fi
      changed_when: false
      when: default_window_manager == "i3"
      become: false

    - name: X Windows | Install xfce4 window manager
      apt:
        name:
          - xfce4
          - xfce4-goodies
        state: present
        update_cache: true
      when: install_window_managers is defined and "xfce4" in install_window_managers

    - name: X Windows | Set default window manager to xfce4 (if is set to default)
      shell: |
        set -o pipefail
        rm -f ~/.xsession
        if ! grep -q "exec startxfce4" ~/.xsession; then
          echo "exec startxfce4" >> ~/.xsession
        fi
      changed_when: false
      when: default_window_manager == "xfce4"
      become: false

    - name: X Windows | Install wmaker window manager
      apt:
        name:
          - wmaker
          - wmaker-common
          - wmaker-data
          - wmaker-utils
        state: present
        update_cache: true
      when: install_window_managers is defined and "wmaker" in install_window_managers

    - name: X Windows | Set default window manager to wmaker (if is set to default)
      shell: |
        set -o pipefail
        rm -f ~/.xsession
        if ! grep -q "exec wmaker" ~/.xsession; then
          echo "exec wmaker" >> ~/.xsession
        fi
      changed_when: false
      when: default_window_manager == "wmaker"
      become: false

    - name: X Windows | Restart xrdp service
      service:
        name: xrdp
        state: restarted
      changed_when: false

    - name: X Windows | Restart xrdp-sesman service
      service:
        name: xrdp-sesman
        state: restarted
      changed_when: false

    - name: X Windows | Restart xorg
      command: "pkill X"
      changed_when: false
      failed_when: false
