---
- name: 1Password | Installation
  hosts: linux
  gather_facts: true
  become: true

  # sudo -s \
  # curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
  # gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
  # echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" |
  # tee /etc/apt/sources.list.d/1password.list
  # mkdir -p /etc/debsig/policies/AC2D62742012EA22/
  # curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | \
  # tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
  # mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
  # curl -sS https://downloads.1password.com/linux/keys/1password.asc | \
  # gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
  # apt update && apt install 1password-cli
  tasks:
    - name: 1Password | Check if is already installed
      command: "which op"
      register: op_check
      changed_when: false
      failed_when: false

    - name: 1Password | Download CLI
      get_url:
        url: https://downloads.1password.com/linux/keys/1password.asc
        dest: /tmp/1password.asc
        mode: 0755
      when: op_check.rc != 0

    - name: 1Password | Add key
      shell: |
        gpg --batch --yes --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg /tmp/1password.asc
      when: op_check.rc != 0

    - name: 1Password | Get architecture
      command: "dpkg --print-architecture"
      register: dpkg_arch
      changed_when: false
      failed_when: false
      when: op_check.rc != 0

    - name: 1Password | Add repository
      apt_repository:
        repo: "deb [arch={{ dpkg_arch.stdout }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ dpkg_arch.stdout }} stable main"
        state: present
        filename: 1password
      when: op_check.rc != 0

    - name: 1Password | Download policy
      get_url:
        url: https://downloads.1password.com/linux/debian/debsig/1password.pol
        dest: /tmp/1password.pol
        mode: 0755
      when: op_check.rc != 0

    - name: 1Password | Create policy directory
      file:
        path: /etc/debsig/policies/AC2D62742012EA22/
        state: directory
        mode: 0755
      when: op_check.rc != 0

    - name: 1Password | Add policy
      copy:
        src: /tmp/1password.pol
        dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
        mode: 0755
      when: op_check.rc != 0

    - name: 1Password | Create keyring directory
      file:
        path: /usr/share/debsig/keyrings/AC2D62742012EA22
        state: directory
        mode: 0755
      when: op_check.rc != 0

    - name: 1Password | Add keyring
      copy:
        src: /tmp/1password.asc
        dest: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
        mode: 0755
      when: op_check.rc != 0

    - name: 1Password | Install CLI
      apt:
        name: 1password-cli
        state: present
        update_cache: true
      when: op_check.rc != 0
