---
# Install asciinema
# https://asciinema.org/
#
# Description: Asciinema is a free and open source solution for recording terminal sessions and sharing them on the web.
#
- name: Asciinema | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Asciinema | Install
      apt:
        name: asciinema
        state: present
        update_cache: yes
