---
# Install Bashtop
# https://github.com/aristocratos/bashtop
#
# Description: Bashtop is a resource monitor that shows usage and stats for processor, memory, disks, network and processes.
#
- name: Bashtop | Installation
  hosts: linux
  gather_facts: true
  become: true

  tasks:
    - name: Bashtop | Install PPA repository (necessary for Ubuntu 23.04 and below)
      apt_repository:
        repo: ppa:bashtop-monitor/bashtop
        state: present
        filename: bashtop
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int <= 23

    - name: Bashtop | Install
      apt:
        name: bashtop
        state: present
        update_cache: true
