---
# Install Bat
# https://github.com/sharkdp/bat
#
# Description: Bat is a cat clone with wings. It provides syntax highlighting for a large number of programming and markup languages.
#
- name: Bat | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Bat | Install
      apt:
        name: bat
        state: present
        update_cache: true

    - name: Bat | Add alias to .bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          alias bat='batcat'
          alias cat='batcat'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - BAT"
      become: false

    - name: Bat | Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: zshrc
      become: false

    - name: Bat | Add alias to .zshrc
      blockinfile:
        path: ~/.zshrc
        block: |
          alias bat='batcat'
          alias cat='batcat'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - BAT"
      when: zshrc.stat.exists
      become: false
