---
- name: Bat | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Bat | Install
      apt:
        name: bat
        state: present
        update_cache: yes

    - name: Bat | Add alias to .bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          alias bat='batcat'
          alias cat='batcat'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - BAT"

    - name: Bat | Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: zshrc

    - name: Bat | Add alias to .zshrc
      blockinfile:
        path: ~/.zshrc
        block: |
          alias bat='batcat'
          alias cat='batcat'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - BAT"
      when: zshrc.stat.exists
