---
- name: CLI Utils Bundle | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: CLI Utils Bundle | Install htop, mc, ncdu, neofetch, pandoc
      apt:
        name:
          - htop
          - mc
          - ncdu
          - neofetch
          - pandoc
        state: present
        update_cache: true

    - name: CLI Utils Bundle | Check if .config/mc exists
      stat:
        path: ~/.config/mc
      register: mc_dir
      become: false

    - name: CLI Utils Bundle | Create .config/mc if it does not exist
      file:
        path: ~/.config/mc
        state: directory
        mode: '0755'
      when: not mc_dir.stat.exists
      become: false

    - name: CLI Utils Bundle | Download mc ini configuation
      get_url:
        url: https://gist.github.com/lpsouza/68b1158119a9d1a74dda7dc560348d50/raw/
        dest: ~/.config/mc/ini
      become: false
