---
- name: .NET | Installation
  hosts: linux
  gather_facts: true
  become: true

  vars:
    dotnet_version: 8.0

  tasks:
    - name: .NET | Download packages from Microsoft
      get_url:
        url: https://packages.microsoft.com/config/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

    - name: .NET | Install packages from Microsoft
      apt:
        deb: /tmp/packages-microsoft-prod.deb

    - name: .NET | Install
      apt:
        name: 'dotnet-sdk-{{ dotnet_version }}'
        state: present
        update_cache: true
      register: dotnet_install

    - name: .NET | Update PATH for .dotnet/tools in .bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          if [ -d "$HOME/.dotnet/tools" ] ; then
            PATH="$HOME/.dotnet/tools:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - DOTNET"
      become: false

    - name: .NET | Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: zshrc
      become: false

    - name: .NET | Update PATH for .dotnet/tools in .zshrc
      blockinfile:
        path: ~/.zshrc
        block: |
          if [ -d "$HOME/.dotnet/tools" ] ; then
            PATH="$HOME/.dotnet/tools:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - DOTNET"
      when: zshrc.stat.exists
      become: false
