---
- name: exa | Installation
  hosts: linux
  gather_facts: true
  become: true

  tasks:
    - name: exa | Install
      apt:
        name: exa
        state: present
      register: exa

    - name: exa | Configure alias for exa to .zshrc if exa is installed
      blockinfile:
        path: ~/.zshrc
        block: |
          alias ls='exa --icons -F -H --group-directories-first'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - exa"
      when: exa is defined and exa.changed
      become: false

    - name: exa | Configure alias for exa to .bashrc if exa is installed
      blockinfile:
        path: ~/.bashrc
        block: |
          alias ls='exa --icons -F -H --group-directories-first'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - exa"
      when: exa is defined and exa.changed
      become: false