---
- name: Home Assistant CLI | Installation
  hosts: linux
  gather_facts: false
  become: true

  vars:
    hass_server: "{{ lookup('env', 'HASS_SERVER') | default('no set', true) }}"
    hass_token: "{{ lookup('env', 'HASS_TOKEN') | default('no set', true) }}"

  tasks:
    - name: Home Assistant CLI | Install dependencies
      apt:
        name:
          - python3-pip
          - python3-venv
        state: present

    - name: Home Assistant CLI | Check if homeassistant-cli is installed
      command: ~/.hassio/bin/hass-cli --version
      register: homeassistant_cli_installed
      changed_when: false
      failed_when: false
      become: false

    - name: Home Assistant CLI | Create virtualenv
      command: python3 -m venv ~/.hassio
      when: homeassistant_cli_installed.rc != 0
      become: false

    - name: Home Assistant CLI | Install
      pip:
        name: homeassistant-cli
        virtualenv: ~/.hassio
        state: present
      register: homeassistant_cli_installer
      when: homeassistant_cli_installed.rc != 0
      become: false

    - name: Home Assistant CLI | Configure (on bashrc)
      blockinfile:
        path: ~/.bashrc
        block: |
          export HASS_SERVER={{ hass_server }}
          export HASS_TOKEN={{ hass_token }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - HASS_CLI_ENV"
      when: hass_server != "no set" and hass_token != "no set"
      become: false

    - name: Home Assistant CLI | Configure python PATH (on bashrc)
      blockinfile:
        path: ~/.bashrc
        block: |
          export PATH=$PATH:~/.local/bin
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Python PATH"
      become: false

    - name: Home Assistant CLI | Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: zshrc_exists
      become: false

    - name: Home Assistant CLI | Configure (on zshrc)
      blockinfile:
        path: ~/.zshrc
        block: |
          export HASS_SERVER={{ hass_server }}
          export HASS_TOKEN={{ hass_token }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - HASS_CLI_ENV"
      when: zshrc_exists.stat.exists and hass_server != "no set" and hass_token != "no set"
      become: false

    - name: Home Assistant CLI | Configure python PATH (on zshrc)
      blockinfile:
        path: ~/.zshrc
        block: |
          export PATH=$PATH:~/.local/bin
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Python PATH"
      when: zshrc_exists.stat.exists
      become: false
