---
- name: Home Assistant CLI | Installation
  hosts: linux
  gather_facts: false

  vars:
    hass_server: "{{ lookup('env', 'HASS_SERVER') | default('no set', true) }}"
    hass_token: "{{ lookup('env', 'HASS_TOKEN') | default('no set', true) }}"

  tasks:
    - name: Home Assistant CLI | Check if homeassistant-cli is installed
      command: hass-cli --version
      register: homeassistant_cli_installed
      changed_when: false
      failed_when: false

    - name: Home Assistant CLI | Install
      pip:
        name: homeassistant-cli
        state: present
      register: homeassistant_cli_installer
      when: homeassistant_cli_installed.rc != 0

    - name: Home Assistant CLI | Configure (on bashrc)
      blockinfile:
        path: ~/.bashrc
        block: |
          export HASS_SERVER={{ hass_server }}
          export HASS_TOKEN={{ hass_token }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - HASS_CLI_ENV"
      when: hass_server != "no set" and hass_token != "no set"

    - name: Home Assistant CLI | Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: zshrc_exists

    - name: Home Assistant CLI | Configure (on zshrc)
      blockinfile:
        path: ~/.zshrc
        block: |
          export HASS_SERVER={{ hass_server }}
          export HASS_TOKEN={{ hass_token }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - HASS_CLI_ENV"
      when: zshrc_exists.stat.exists and hass_server != "no set" and hass_token != "no set"
