---
# Install htop
# https://htop.dev/
#
# Description: htop is an interactive process viewer for Unix systems.
#
- name: htop | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: htop | Install
      apt:
        name: htop
        state: present
        update_cache: true
