---
# Install iputils-ping
#
# Description: The iputils-ping package contains tools for network testing and management, including ping.
#
- name: IPUtils-Ping | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: IPUtils-Ping | Install iputils-ping
      apt:
        name:
          - iputils-ping
        state: present
        update_cache: true
