---
# Install jq
# https://stedolan.github.io/jq/
#
# Description: jq is a lightweight and flexible command-line JSON processor.
#
- name: jq | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: jq | Install jq
      apt:
        name: jq
        state: present
        update_cache: true
