---
- name: K3S | Installation
  hosts: linux
  gather_facts: false
  become: true

  vars:
    k3s_token: "{{ lookup('env', 'K3S_TOKEN') | default('no set', true) }}"

  tasks:
    - name: K3S | Check if is already installed
      command: which k3s
      register: k3s_check
      changed_when: false
      failed_when: false

    - name: K3S | Download installer script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install.sh
        mode: "0755"
      when: k3s_check.rc == 1

    - name: K3S | Install (server)
      shell: |
        if [ "{{ k3s_token }}" != "no set" ]; then
          export K3S_TOKEN="{{ k3s_token }}"
        fi
        /tmp/install.sh server --write-kubeconfig-mode 644
      when: k3s_check.rc == 1
