---
- name: K3S | Installation
  hosts: linux
  gather_facts: false
  become: true

  vars:
    k3s_url: "{{ lookup('env', 'K3S_URL') | default('no set', true) }}"
    k3s_token: "{{ lookup('env', 'K3S_TOKEN') | default('no set', true) }}"

  tasks:
    - name: K3S | Check if is already installed
      command: which k3s
      register: k3s_check
      changed_when: false
      failed_when: false

    - name: K3S | Download installer script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install.sh
        mode: "0755"
      when: k3s_check.rc == 1

    - name: K3S | Install (server)
      command: /tmp/install.sh --write-kubeconfig-mode 644 --write-kubeconfig /root/.kube/config
      when: k3s_check.rc == 1 and k3s_url == "no set" and k3s_token == "no set"

    - name: K3S | Install (agent)
      shell: |
        export K3S_URL={{ k3s_url }}
        export K3S_TOKEN={{ k3s_token }}
        /tmp/install.sh --write-kubeconfig-mode 644 --write-kubeconfig /root/.kube/config
      when: k3s_check.rc == 1 and k3s_url != "no set" and k3s_token != "no set"
