---
- name: Keychain | Installation
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Keychain | Install
      apt:
        name: keychain
        state: present

    - name: Keychain | Check if is already added on oh-my-zsh plugins (ZSH)
      shell: grep -E "^plugins=\(.*keychain.*\)" ~/.zshrc
      register: keychain_plugin_check
      changed_when: false
      failed_when: false
      become: false

    - name: Keychain | Add keychain to oh-my-zsh plugins (ZSH)
      lineinfile:
        path: ~/.zshrc
        regexp: '^plugins=\((.*)\)'
        line: 'plugins=(\1 keychain)'
        backrefs: true
      become: false
      when: keychain_plugin_check.rc != 0

    - name: Keychain | Configure zstyle sources on oh-my-zsh (ZSH)
      blockinfile:
        dest: ~/.zshrc
        insertbefore: plugins=\(
        block: |
          zstyle :omz:plugins:keychain agents ssh
          zstyle :omz:plugins:keychain identities id_rsa
          zstyle :omz:plugins:keychain options --nogui --quiet
        marker: "# {mark} ANSIBLE MANAGED BLOCK - keychain"
      become: false

    - name: Keychain | Check if is already added on .bashrc (BASH)
      shell: grep -E "^eval \$(keychain --quiet --agents ssh id_rsa)" ~/.bashrc
      register: keychain_bashrc_check
      changed_when: false
      failed_when: false
      become: false

    - name: Keychain | Add keychain to .bashrc (BASH)
      lineinfile:
        path: ~/.bashrc
        line: 'eval $(keychain --quiet --agents ssh id_rsa)'
      become: false
      when: keychain_bashrc_check.rc != 0
