---
# Install Kubectl
# https://kubernetes.io/docs/tasks/tools/install-kubectl/
#
# Description: Kubectl is a command-line tool for interacting with Kubernetes clusters.
#
- name: Kubectl | Installation
  hosts: linux
  gather_facts: false
  become: true

  vars:
    kubectl_version: 1.27.4

  tasks:
    - name: Kubectl | Download binary to /usr/local/bin
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 0755
