---
# Install Midnight Commander
# https://midnight-commander.org/
#
# Description: Midnight Commander is a free cross-platform orthodox file manager.
#
- name: Midnight Commander | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Midnight Commander | Install
      apt:
        name: mc
        state: present
        update_cache: true
