---
- name: Install mongosh
  hosts: linux
  become: true
  gather_facts: false

  vars:
    mongosh_version: "2.1.5"

  tasks:
    - name: Check if mongosh is already installed
      shell: mongosh --version
      register: mongosh_package_status
      changed_when: false
      failed_when: false

    - name: Download mongosh
      get_url:
        url: https://downloads.mongodb.com/compass/mongodb-mongosh_{{ mongosh_version }}_amd64.deb
        dest: /tmp/mongosh_install.deb
      when: "mongosh_package_status.rc != 0"

    - name: Install mongosh
      apt:
        deb: /tmp/mongosh_install.deb
        state: present
      when: "mongosh_package_status.rc != 0"
