---
- name: Install MongoDB Shell
  hosts: linux
  become: true
  gather_facts: false

  vars:
    mongosh_version: "2.2.10"

  tasks:
    - name: Download MongoDB Shell
      get_url:
        url: https://downloads.mongodb.com/compass/mongodb-mongosh_{{ mongosh_version }}_amd64.deb
        dest: /tmp/mongodb-mongosh_{{ mongosh_version }}_amd64.deb

    - name: Install MongoDB Shell
      apt:
        deb: /tmp/mongodb-mongosh_{{ mongosh_version }}_amd64.deb
        state: present
