---
# Install Ncdu
# https://dev.yorhel.nl/ncdu
#
# Description: Ncdu is a disk usage analyzer with an ncurses interface.
#
- name: Ncdu | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Ncdu | Install
      apt:
        name: ncdu
        state: present
        update_cache: true
