---
# Install Neofetch
#
# Description: Neofetch is a command-line system information tool written in bash 3.2+.
#
- name: Neofetch | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Neofetch | Install
      apt:
        name: neofetch
        state: present
        update_cache: true
