---
- name: Neovim | Installation
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Neovim | Install dependencies
      apt:
        name: fuse
        state: present
        update_cache: true

    - name: Neovim | Download appimage
      get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
        dest: /usr/local/bin/nvim
        mode: 0755

    - name: Neovim | Check if configuration directory exists
      stat:
        path: ~/.config
      register: config_directory_stat
      failed_when: false
      become: false

    - name: Neovim | If not exists, create configuration directory
      file:
        path: ~/.config
        state: directory
        mode: "0755"
      when: not config_directory_stat.stat.exists
      become: false

    - name: Neovim | Clone configuration repository
      git:
        repo: "https://github.com/lpsouza/nvim-config.git"
        dest: ~/.config/nvim
        version: main
      become: false
