---
- name: NVM | Installation
  hosts: linux
  gather_facts: false

  vars:
    nvm_version: "0.38.0"

  tasks:
    - name: NVM | Check if is already installed
      stat:
        path: ~/.nvm
      register: nvm_directory_stat
      failed_when: false

    - name: NVM | Download
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
        dest: /tmp/nvm.sh
        mode: '0755'
      when: not nvm_directory_stat.stat.exists

    - name: NVM | Install nvm
      script: /tmp/nvm.sh
      when: not nvm_directory_stat.stat.exists

    - name: NVM | Check if nvm is configured on .bashrc (BASH)
      shell: grep -E "^export NVM_DIR=" ~/.bashrc
      register: nvm_bashrc_check
      changed_when: false
      failed_when: false

    - name: NVM | Configure nvm on .bashrc (BASH)
      lineinfile:
        path: ~/.bashrc
        regexp: '^export NVM_DIR='
        line: 'export NVM_DIR="$HOME/.nvm"'
        backrefs: true
      when: nvm_bashrc_check.rc != 0

    - name: NVM | Check if .zshrc exists (ZSH)
      stat:
        path: ~/.zshrc
      register: zshrc_check
      failed_when: false

    - name: NVM | Check if nvm plugin is already added to oh-my-zsh (ZSH)
      shell: grep -E "^plugins=\(.*nvm.*\)" ~/.zshrc
      register: nvm_plugin_check
      when: zshrc_check.stat.exists
      changed_when: false
      failed_when: false

    - name: NVM | Add nvm to oh-my-zsh plugins (ZSH)
      lineinfile:
        path: ~/.zshrc
        regexp: '^plugins=\((.*)\)'
        line: 'plugins=(\1 nvm)'
        backrefs: true
      when: nvm_plugin_check.rc != 0 and zshrc_check.stat.exists


    - name: NVM | Configure zstyle sources on oh-my-zsh (ZSH)
      blockinfile:
        dest: ~/.zshrc
        insertbefore: plugins=\(
        block: |
          zstyle ':omz:plugins:nvm' lazy yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - nvm"
      when: zshrc_check.stat.exists

    - name: NVM | Configure nvm on .zshrc (ZSH)
      blockinfile:
        dest: ~/.zshrc
        block: |
          export NVM_DIR="$HOME/.nvm"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - nvm dir"
      when: zshrc_check.stat.exists