---
# Install Powershell on Linux
# https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux
#
# Description: PowerShell is a task automation and configuration management framework from Microsoft, consisting of a command-line shell and associated scripting language.
#
- name: Powershell | Installation
  hosts: linux
  gather_facts: true
  become: true

  tasks:
    - name: Powershell | Download packages from Microsoft
      get_url:
        url: https://packages.microsoft.com/config/{{ ansible_distribution | lower }}/{{ ansible_distribution_version }}/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb

    - name: Powershell | Install packages from Microsoft
      apt:
        deb: /tmp/packages-microsoft-prod.deb

    - name: Powershell | Install
      apt:
        name: powershell
        state: present
        update_cache: true
