---
- name: Python3 | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Python3 | Install
      apt:
        name:
          - python-is-python3
          - python3-pip
        state: present
        update_cache: yes
