---
- name: Terraform | Installation
  hosts: linux
  gather_facts: true
  become: true

  vars:
    terraform_version: 1.7.3

  tasks:
    - name: Terraform | Download
      get_url:
        url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /tmp/terraform_{{ terraform_version }}_linux_amd64.zip
        mode: 0644

    - name: Terraform | Unzip
      unarchive:
        src: /tmp/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        mode: 0755
        creates: /usr/local/bin/terraform
