---
- name: Web CLI Bundle | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Web CLI Bundle | Install curl, elinks, jq, wget
      apt:
        name:
          - curl
          - elinks
          - jq
          - wget
        state: present
        update_cache: true
