---
# Install wget
# https://www.gnu.org/software/wget/
#
# Description: GNU Wget is a free software package for retrieving files using HTTP, HTTPS, FTP, and FTPS.
#
- name: Wget | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Wget | Install wget
      apt:
        name: wget
        state: present
        update_cache: true
