---
# Install whois
# https://en.wikipedia.org/wiki/WHOIS
#
# Description: WHOIS is a query and response protocol that is widely used for querying databases that store the registered users or assignees of an Internet resource, such as a domain name, an IP address block or an autonomous system, but is also used for a wider range of other information.
#
- name: Whois | Install
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Whois | Install whois
      apt:
        name:
          - whois
        state: present
        update_cache: true
