---
- name: AWS CLI | Installation
  hosts: linux
  gather_facts: true
  become: true

  tasks:
    - name: AWS CLI | Installing dependencies
      apt:
        name: unzip
        state: present

    - name: AWS CLI | Checking if is already installed
      command: "which aws"
      register: aws_cli_check
      changed_when: false
      failed_when: false

    - name: AWS CLI | Download AWS CLI
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: 0755
      when: aws_cli_check.rc != 0
      notify:
        - AWS CLI | Unzip
        - AWS CLI | Install

  handlers:
    - name: AWS CLI | Unzip
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: true
        creates: /tmp/aws

    - name: AWS CLI | Install
      command: /tmp/aws/install
