---
- name: Install AWS CLI
  hosts: linux
  become: true
  gather_facts: true

  tasks:
    - name: Download AWS CLI
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: 0755
      notify:
        - Unzip AWS CLI
        - Install AWS CLI

  handlers:
    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: true
        creates: /tmp/aws

    - name: Install AWS CLI
      command: /tmp/aws/install
