---
- name: Bashtop | Installation
  hosts: linux
  gather_facts: true
  become: true

  tasks:
    - name: Bashtop | Install PPA repository
      apt_repository:
        repo: ppa:bashtop-monitor/bashtop
        state: present
        filename: bashtop

    - name: Bashtop | Install
      apt:
        name: bashtop
        state: present
        update_cache: true
