---
- name: Bash | Extra configurations
  hosts: linux
  gather_facts: false

  tasks:
    - name: Bash | Configure bin folder to PATH
      blockinfile:
        path: ~/.bashrc
        block: |
          if [ -d "$HOME/bin" ] ; then
            PATH="$HOME/bin:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - bin folder"

    - name: Bash | Configure .local/bin folder to PATH
      blockinfile:
        path: ~/.bashrc
        block: |
          if [ -d "$HOME/.local/bin" ] ; then
            PATH="$HOME/.local/bin:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - .local/bin folder"
