---
- name: Install bashtop
  hosts: linux
  become: true
  gather_facts: true

  tasks:
    - name: Install bashtop PPA repository
      apt_repository:
        repo: ppa:bashtop-monitor/bashtop
        state: present
        filename: bashtop
      when: ansible_distribution == 'Ubuntu'

    - name: Install bashtop
      apt:
        name: bashtop
        state: present
        update_cache: true
      when: ansible_distribution == 'Ubuntu'

    - name: Install bashtop (btop)
      apt:
        name: btop
        state: present
        update_cache: true
      when: ansible_distribution == 'Debian'
