---
- name: Install dotnet
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: Search for dotnet-sdk-7.0 on apt-cache
      command: apt-cache search dotnet-sdk-7.0
      register: dotnet_sdk_7_0
      failed_when: false
      changed_when: false

    - name: Download packages-microsoft-prod.deb
      get_url:
        url: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
      when: dotnet_sdk_7_0.stdout.find('dotnet-sdk-7.0') == -1

    - name: Install packages-microsoft-prod.deb
      command: dpkg -i /tmp/packages-microsoft-prod.deb
      when: dotnet_sdk_7_0.stdout.find('dotnet-sdk-7.0') == -1

    - name: Install dotnet-sdk-7.0
      apt:
        name: dotnet-sdk-7.0
        state: present
        update_cache: true

    - name: Update PATH for .dotnet/tools in .zshrc
      blockinfile:
        path: ~/.zshrc
        block: |
          if [ -d "$HOME/.dotnet/tools" ] ; then
            PATH="$HOME/.dotnet/tools:$PATH"
          fi
        marker: "# {mark} ANSIBLE MANAGED BLOCK - DOTNET"
      become: false
