---
- name: Install dotnet
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Search for dotnet-sdk-7.0 on apt-cache
      shell: apt-cache search dotnet-sdk-7.0
      register: dotnet_sdk_7_0
      failed_when: false
      changed_when: false

    - name: Download packages-microsoft-prod.deb
      get_url:
        url: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
      when: dotnet_sdk_7_0.stdout.find('dotnet-sdk-7.0') == -1

    - name: Install packages-microsoft-prod.deb
      shell: dpkg -i /tmp/packages-microsoft-prod.deb
      when: dotnet_sdk_7_0.stdout.find('dotnet-sdk-7.0') == -1

    - name: Install dotnet-sdk-7.0
      apt:
        name: dotnet-sdk-7.0
        state: present
        update_cache: yes
