---
- name: Configure Git username and email
  hosts: linux
  gather_facts: false

  vars:
    git_username: "{{ lookup('env', 'GIT_USERNAME') }}"
    git_email: "{{ lookup('env', 'GIT_EMAIL') }}"

  tasks:
    - name: Check Git username configuration
      git_config:
        scope: global
        name: user.name
      register: git_username_output
      changed_when: false

    - name: Set Git username
      git_config:
        scope: global
        name: user.name
        value: "{{ git_username }}"
      when: git_username_output.value is not defined

    - name: Check Git email configuration
      git_config:
        scope: global
        name: user.email
      register: git_email_output
      changed_when: false

    - name: Set Git email
      git_config:
        scope: global
        name: user.email
        value: "{{ git_email }}"
      when: git_email_output.value is not defined

    - name: Check Git pull.rebase configuration set to false (merge)
      git_config:
        scope: global
        name: pull.rebase
      register: git_pull_rebase_output
      changed_when: false

    - name: Set Git pull.rebase to false (merge)
      git_config:
        scope: global
        name: pull.rebase
        value: "false"
      when: git_pull_rebase_output.value is not defined
