---
- name: GNS3 | Installation
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: GNS3 | Install PPA repository
      apt_repository:
        repo: ppa:gns3/ppa
        state: present
        update_cache: true

    - name: GNS3 | Install Server
      apt:
        name: gns3-server
        state: present
        update_cache: true

    - name: GNS3 | Install GUI
      apt:
        name: gns3-gui
        state: present
        update_cache: true

    - name: GNS3 | Install VNC Viewer and Gnome Terminal (for console)
      apt:
        name:
          - tigervnc-viewer
          - gnome-terminal
        state: present
        update_cache: true

    - name: GNS3 | Add user to kvm group
      user:
        name: "{{ ansible_user }}"
        groups: kvm
        append: true
        state: present
