---
- name: Install i3 window manager
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Install xorg, xinit and i3
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - xorg
        - xinit
        - i3
