---
- name: Initial setup
  hosts: linux
  become: true
  gather_facts: true

  tasks:
    - name: Touching .hushlogin file
      file:
        path: .hushlogin
        state: touch
        mode: '0644'
      become: false

    - name: Check if universe repository is enabled
      shell: |
        set -o pipefail
        apt-cache policy | grep universe
      register: universe_repository
      changed_when: false
      failed_when: false
      check_mode: false


    - name: Add universe repository on Ubuntu
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        state: present
        update_cache: true
      when: universe_repository.rc != 0 and ansible_distribution == 'Ubuntu'


    - name: Check if multiverse repository is enabled
      shell: |
        set -o pipefail
        apt-cache policy | grep multiverse
      register: multiverse_repository
      changed_when: false
      failed_when: false
      check_mode: false


    - name: Add multiverse repository on Ubuntu
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
        state: present
        update_cache: true
      when: multiverse_repository.rc != 0 and ansible_distribution == 'Ubuntu'


    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
        update_cache: true
      tags: upgrade

    - name: Install essential packages
      apt:
        name:
          - ansible-lint
          - apt-transport-https
          - apt-utils
          - asciinema
          - build-essential
          - ca-certificates
          - coreutils
          - csvkit
          - curl
          - fuse
          - elinks
          - htop
          - iputils-ping
          - jq
          - libasound2
          - libgtk-3-0
          - libnss3
          - lsb-release
          - mc
          - mtr
          - nano
          - ncdu
          - neofetch
          - net-tools
          - pandoc
          - python-is-python3
          - python3-pip
          - software-properties-common
          - sqlite3
          - unzip
          - wget
          - whois
          - zip
        state: present
        update_cache: true
