---
- name: Install k9s
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: Check if k9s is already installed
      stat:
        path: /usr/local/bin/k9s
      register: k9s_installed

    - name: Install k9s
      get_url:
        url: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
        dest: /tmp/k9s_Linux_amd64.tar.gz
        mode: 0644
      when: not k9s_installed.stat.exists

    - name: Unarchive k9s
      unarchive:
        src: /tmp/k9s_Linux_amd64.tar.gz
        dest: /tmp
        remote_src: true
        mode: 0755
      when: not k9s_installed.stat.exists

    - name: Move k9s to /usr/local/bin
      copy:
        src: /tmp/k9s
        dest: /usr/local/bin/k9s
        mode: 0755
      when: not k9s_installed.stat.exists
