---
- name: Install Neovim
  hosts: linux
  gather_facts: false

  tasks:
    - name: Ensure ~/.local/bin directory exists
      file:
        path: ~/.local/bin
        state: directory
        mode: 0755

    - name: Download nvim.appimage
      get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
        dest: ~/.local/bin/nvim
        mode: 0755

    - name: Clone configuration repository
      git:
        repo: "https://github.com/lpsouza/nvim-config.git"
        dest: ~/.config/nvim
        version: main
