---
- name: Configure passwordless
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: Add sudoers entry for passwordless sudo
      blockinfile:
        path: /etc/sudoers
        block: |
          {{ ansible_user }} ALL=(ALL) NOPASSWD:ALL
        marker: "# {mark} ANSIBLE MANAGED BLOCK - passwordless sudo"

