- name: Install my public key
  hosts: linux
  gather_facts: false

  vars:
    pubkey: "{{ lookup('env', 'PUBKEY') }}"

  tasks:
    - name: Check if public key is already added
      shell: grep -E "^ssh-rsa.*{{ pubkey }}" ~/.ssh/authorized_keys
      register: pubkey_check
      changed_when: false
      failed_when: false


    - name: Add public key to authorized_keys
      lineinfile:
        path: ~/.ssh/authorized_keys
        line: "{{ pubkey }}"
        create: true
        mode: 0600
      when: pubkey_check.rc != 0

