---
- name: OpenSSH Server | Installation
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: OpenSSH Server | Install
      apt:
        name: openssh-server
        state: present
        update_cache: true

    - name: OpenSSH Server | Check if is a WSL instance
      command: "grep -qEi '(Microsoft|WSL)' /proc/version"
      register: is_wsl
      failed_when: false
      changed_when: false

    - name: OpenSSH Server | If is a WSL instance, enable systemd
      ini_file:
        path: /etc/wsl.conf
        section: "boot"
        option: "systemd"
        value: "true"
        state: present
        mode: 0644
      when: is_wsl.rc == 0

    - name: OpenSSH Server | Check if systemd is running
      command: "ps -p 1 -o comm="
      register: init_process
      failed_when: false
      changed_when: false

    - name: OpenSSH Server | Enable service (systemd)
      service:
        name: ssh
        enabled: true
        state: started
      when: init_process.stdout == "systemd"
