---
- name: Install Terraform
  hosts: linux
  become: true
  gather_facts: true

  vars:
    - terraform_version: 1.5.5

  tasks:
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /tmp/terraform_{{ terraform_version }}_linux_amd64.zip
        mode: 0644

    - name: Unzip Terraform
      unarchive:
        src: /tmp/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: true
        mode: 0755
        creates: /usr/local/bin/terraform
