- name: Install tmux
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: Install tmux
      apt:
        name: tmux
        state: present
        update_cache: true

    - name: Clone tpm (tmux plugin manager) repository
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.tmux/plugins/tpm"
        version: master
      become: false


    - name: Copy tmux.conf from gist
      get_url:
        url: https://gist.github.com/lpsouza/6534fd264197963e86dce01ece9f63d1/raw
        dest: ~/.tmux.conf
        mode: "0644"
      become: false

