---
- name: Tmux | Installation
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Tmux | Install
      apt:
        name: tmux
        state: present
        update_cache: true

    - name: Tmux | Install Tmux Plugin Manager
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "~/.tmux/plugins/tpm"
        version: master
      become: false


    - name: Tmux | Download tmux custom configuration
      get_url:
        url: https://gist.github.com/lpsouza/6534fd264197963e86dce01ece9f63d1/raw
        dest: ~/.tmux.conf
        mode: "0644"
      become: false
