---
- name: Timezone | Configuration
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Timezone | Set timezone to America/Sao_Paulo
      timezone:
        name: America/Sao_Paulo
