---
- name: X Windows | Installation
  hosts: linux
  gather_facts: false
  become: true

  vars:
    install_window_managers: ["i3", "xfce4", "wmaker"]
    default_window_manager: "{{ lookup('env', 'DEFAULT_WINDOW_MANAGER') | default('i3', true) }}"

  tasks:
    - name: X Windows | Install X Window System (base)
      apt:
        name:
          - xorg
          - xinit
          - xrdp
        state: present
        update_cache: true

    - name: X Windows | Install i3 window manager
      apt:
        name:
          - i3
          - i3blocks
        state: present
        update_cache: true
      when: install_window_managers is defined and "i3" in install_window_managers

    - name: X Windows | Set default window manager to i3 (if is set to default)
      shell: |
        set -o pipefail
        if [ "$(update-alternatives --display x-session-manager | grep 'link currently points to')" != "/usr/bin/i3" ]; then
          update-alternatives --set x-session-manager /usr/bin/i3
        fi
        if [ "$(update-alternatives --display x-window-manager | grep 'link currently points to')" != "/usr/bin/i3" ]; then
          update-alternatives --set x-window-manager /usr/bin/i3
        fi
      changed_when: false
      when: default_window_manager == "i3"

    - name: X Windows | Install xfce4 window manager
      apt:
        name:
          - xfce4
          - xfce4-goodies
        state: present
        update_cache: true
      when: install_window_managers is defined and "xfce4" in install_window_managers

    - name: X Windows | Set default window manager to xfce4 (if is set to default)
      shell: |
        set -o pipefail
        if [ "$(update-alternatives --display x-session-manager | grep 'link currently points to')" != "/usr/bin/startxfce4" ]; then
          update-alternatives --set x-session-manager /usr/bin/startxfce4
        fi
        if [ "$(update-alternatives --display x-window-manager | grep 'link currently points to')" != "/usr/bin/xfwm4" ]; then
          update-alternatives --set x-window-manager /usr/bin/xfwm4
        fi
      changed_when: false
      when: default_window_manager == "xfce4"

    - name: X Windows | Install wmaker window manager
      apt:
        name:
          - wmaker
          - wmaker-common
          - wmaker-data
          - wmaker-utils
        state: present
        update_cache: true
      when: install_window_managers is defined and "wmaker" in install_window_managers

    - name: X Windows | Set default window manager to wmaker (if is set to default)
      shell: |
        set -o pipefail
        if [ "$(update-alternatives --display x-window-manager | grep 'link currently points to')" != "/usr/bin/wmaker" ]; then
          update-alternatives --set x-window-manager /usr/bin/wmaker
        fi
      changed_when: false
      when: default_window_manager == "wmaker"

    - name: X Windows | Restart xrdp service
      service:
        name: xrdp
        state: restarted
      changed_when: false

    # - name: X Windows | Install X Window System (i3, xfce4, xorg, xinit, xrdp, xserver-xephyr and kitty)
    #   apt:
    #     name:
    #       - i3
    #       - i3blocks
    #       - xfce4
    #       - xorg
    #       - xinit
    #       - xrdp
    #       - xserver-xephyr
    #       - kitty
    #     state: present
    #     update_cache: true

    # - name: X Windows | Ensure default terminal is set to kitty
    #   shell: |
    #     set -o pipefail
    #     if [ "$(update-alternatives --display x-terminal-emulator | grep 'link currently points to')" != "/usr/bin/kitty" ]; then
    #       update-alternatives --set x-terminal-emulator /usr/bin/kitty
    #     fi
    #   changed_when: false

    # - name: X Windows | Ensure default x-session-manager is set to xfce4
    #   shell: |
    #     set -o pipefail
    #     if [ "$(update-alternatives --display x-session-manager | grep 'link currently points to')" != "/usr/bin/startxfce4" ]; then
    #       update-alternatives --set x-session-manager /usr/bin/startxfce4
    #     fi
    #   changed_when: false

    # - name: X Windows | Ensure default x-window-manager is set to xfwm4
    #   shell: |
    #     set -o pipefail
    #     if [ "$(update-alternatives --display x-window-manager | grep 'link currently points to')" != "/usr/bin/xfwm4" ]; then
    #       update-alternatives --set x-window-manager /usr/bin/xfwm4
    #     fi
    #   changed_when: false

    # - name: X Windows | Check if ~/.config/i3status exists
    #   stat:
    #     path: ~/.config/i3status
    #   register: i3status

    # - name: X Windows | Create ~/.config/i3status if it doesn't exist
    #   file:
    #     path: ~/.config/i3status
    #     state: directory
    #     mode: 0755
    #   when: not i3status.stat.exists
    #   become: false

    # - name: X Windows | Copy i3status config from gist
    #   get_url:
    #     url: https://gist.github.com/lpsouza/408b2d8142caeb27f8dc6645b84fe04d/raw
    #     dest: ~/.config/i3status/config
    #     mode: "0644"
    #   become: false
