---
- name: Install X Window System and friends
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Install X Window System and friends
      apt:
        name:
          - i3
          - i3blocks
          - xorg
          - xinit
          - xrdp
          - xserver-xephyr
          - kitty
        state: present
        update_cache: true

    - name: Change default terminal to kitty
      command: update-alternatives --set x-terminal-emulator /usr/bin/kitty
      changed_when: true

    - name: Ensure ~/.local/bin directory exists
      file:
        path: ~/.local/bin
        state: directory
        mode: 0755
      become: false

    - name: Create i3wm script
      copy:
        dest: ~/.local/bin/i3wm
        content: |
          #!/bin/bash
          Xephyr -br -fullscreen -resizeable -dpi 200 :20 &
          sleep 5
          DISPLAY=:20 i3 &
        mode: 0755
      become: false
