---
- name: Install X Window System and friends
  hosts: linux
  become: true
  gather_facts: false

  tasks:
    - name: Install X Window System (i3, xfce4, xorg, xinit, xrdp, xserver-xephyr and kitty)
      apt:
        name:
          - i3
          - i3blocks
          - xfce4
          - xorg
          - xinit
          - xrdp
          - xserver-xephyr
          - kitty
        state: present
        update_cache: true

    - name: Ensure default terminal is set to kitty
      shell: |
        set -o pipefail
        if [ "$(update-alternatives --display x-terminal-emulator | grep 'link currently points to')" != "/usr/bin/kitty" ]; then
          update-alternatives --set x-terminal-emulator /usr/bin/kitty
        fi
      changed_when: false

    - name: Ensure default x-session-manager is set to xfce4
      shell: |
        set -o pipefail
        if [ "$(update-alternatives --display x-session-manager | grep 'link currently points to')" != "/usr/bin/startxfce4" ]; then
          update-alternatives --set x-session-manager /usr/bin/startxfce4
        fi
      changed_when: false

    - name: Ensure default x-window-manager is set to xfwm4
      shell: |
        set -o pipefail
        if [ "$(update-alternatives --display x-window-manager | grep 'link currently points to')" != "/usr/bin/xfwm4" ]; then
          update-alternatives --set x-window-manager /usr/bin/xfwm4
        fi
      changed_when: false

    - name: Ensure ~/.local/bin directory exists
      file:
        path: ~/.local/bin
        state: directory
        mode: 0755
      become: false

    - name: Create i3wm script
      copy:
        dest: ~/.local/bin/i3wm
        content: |
          #!/bin/bash
          unset DBUS_SESSION_BUS_ADDRESS
          unset XDG_RUNTIME_DIR
          Xephyr -br -ac -noreset -fullscreen -resizeable :20 1>/dev/null 2>&1 &
          sleep 5
          export DISPLAY=:20
          i3 1>/dev/null 2>&1
          pkill Xephyr
        mode: 0755
      become: false

    - name: Create desktop shortcut to i3wm script
      copy:
        dest: /usr/share/applications/i3wm.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=i3wm
          Terminal=false
          NoDisplay=false
          GenericName=i3wm
          Comment=i3wm
          Exec=/home/{{ ansible_user }}/.local/bin/i3wm
        mode: 0644

    - name: Check if ~/.config/i3status exists
      stat:
        path: ~/.config/i3status
      register: i3status

    - name: Create ~/.config/i3status if it doesn't exist
      file:
        path: ~/.config/i3status
        state: directory
        mode: 0755
      when: not i3status.stat.exists
      become: false

    - name: Copy i3status config from gist
      get_url:
        url: https://gist.github.com/lpsouza/408b2d8142caeb27f8dc6645b84fe04d/raw
        dest: ~/.config/i3status/config
        mode: "0644"
      become: false

