---
- name: Install X Window System and friends
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Install X Window System and friends
      apt:
        name:
          - i3
          - i3blocks
          - xorg
          - xinit
          - xrdp
          - xserver-xephyr
          - kitty
        state: present
        update_cache: true

    - name: Ensure default terminal is set to kitty
      shell: |
        if [ "$(update-alternatives --display x-terminal-emulator | grep 'link currently points to')" != "/usr/bin/kitty" ]; then
          update-alternatives --set x-terminal-emulator /usr/bin/kitty
        fi
      changed_when: false

    - name: Ensure ~/.local/bin directory exists
      file:
        path: ~/.local/bin
        state: directory
        mode: 0755
      become: false

    - name: Create i3wm script
      copy:
        dest: ~/.local/bin/i3wm
        content: |
          #!/bin/bash
          unset DBUS_SESSION_BUS_ADDRESS
          unset XDG_RUNTIME_DIR
          Xephyr -br -ac -noreset -fullscreen -resizeable :20 1>/dev/null 2>&1 &
          sleep 5
          export DISPLAY=:20
          xrdb -merge ~/.Xresources
          i3 1>/dev/null 2>&1
          pkill Xephyr
        mode: 0755
      become: false

    - name: "Add dpi to 180 on .Xresources"
      lineinfile:
        path: ~/.Xresources
        line: "Xft.dpi: 180"
        insertafter: EOF
      become: false

    - name: Create desktop shortcut to i3wm script
      copy:
        dest: /usr/share/applications/i3wm.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=i3wm
          Terminal=false
          NoDisplay=false
          GenericName=i3wm
          Comment=i3wm
          Exec=/home/lpsouza/.local/bin/i3wm
        mode: 0644

    - name: Copy i3status config from gist
      get_url:
        url: https://gist.github.com/lpsouza/408b2d8142caeb27f8dc6645b84fe04d/raw
        dest: ~/.config/i3status/config
        mode: "0644"
      become: false
      tags: config
