---
- name: Install X Window System
  hosts: localhost
  remote_user: lpsouza
  become: true
  become_user: root
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Install i3, xorg, xinit, xrdp, xephyr and kitty
      apt:
        name: ['i3', 'xorg', 'xinit', 'xrdp', 'xserver-xephyr', 'kitty']
        state: present
        update_cache: true

    - name: Change default terminal to kitty
      command: update-alternatives --set x-terminal-emulator /usr/bin/kitty
      changed_when: true

    - name: Create startx-xephyr script
      copy:
        dest: /usr/local/bin/startx-xephyr
        content: |
          #!/bin/bash
          Xephyr -br -fullscreen -resizable :20 &
          sleep 5
          DISPLAY=:20 startx &
        mode: 0755
